name: Multiple Branches for Pull Request Workflow

on: 
  pull_request:
    branches:
      - feature
      - main

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: linux
        run: |
          echo "This job is running on an ubuntu runner"
          echo "Runner OS is $RUNNER_OS"
